function ret = JCoM(x)

ret = [[1,0,0,0,cos(x(5))*(0.01+cos(x(7))*cos(x(8)))-...
sin(x(5))*(cos(x(8))*sin(x(6))*sin(x(7))+cos(x(6))*sin(x(8))),...
cos(x(5))*(cos(x(6))*cos(x(8))*sin(x(7))-sin(x(6))*sin(x(8))),...
cos(x(5))*cos(x(7))*cos(x(8))*sin(x(6))-cos(x(8))*sin(x(5))*sin(x(7)),...
-(cos(x(7))*sin(x(5))*sin(x(8)))+cos(x(5))*(cos(x(6))*cos(x(8))-...
sin(x(6))*sin(x(7))*sin(x(8)))];...
[0,1,0,-0.01*cos(x(4))*cos(x(5))-...
cos(x(8))*(-(cos(x(6))*sin(x(4))*sin(x(7)))+...
cos(x(4))*(cos(x(5))*cos(x(7))-sin(x(5))*sin(x(6))*sin(x(7))))+...
cos(x(4))*cos(x(6))*sin(x(5))*sin(x(8))-sin(x(4))*sin(x(6))*sin(x(8)),...
0.01*sin(x(4))*sin(x(5))-cos(x(8))*sin(x(4))*(-(cos(x(7))*sin(x(5)))-...
cos(x(5))*sin(x(6))*sin(x(7)))+cos(x(5))*cos(x(6))*sin(x(4))*...
sin(x(8)),-(cos(x(8))*(-(cos(x(6))*sin(x(4))*sin(x(5))*sin(x(7)))-...
cos(x(4))*sin(x(6))*sin(x(7))))+cos(x(4))*cos(x(6))*sin(x(8))-...
sin(x(4))*sin(x(5))*sin(x(6))*sin(x(8)),...
-(cos(x(8))*(cos(x(4))*cos(x(6))*cos(x(7))+...
sin(x(4))*(-(cos(x(7))*sin(x(5))*sin(x(6)))-cos(x(5))*sin(x(7))))),...
cos(x(6))*cos(x(8))*sin(x(4))*sin(x(5))+cos(x(4))*cos(x(8))*sin(x(6))+...
(cos(x(4))*cos(x(6))*sin(x(7))+sin(x(4))*(cos(x(5))*cos(x(7))-...
sin(x(5))*sin(x(6))*sin(x(7))))*sin(x(8))];...
[0,0,1,cos(x(4))*(-(cos(x(6))*cos(x(8))*sin(x(7)))+...
sin(x(6))*sin(x(8)))-sin(x(4))*...
(cos(x(5))*(0.01+cos(x(7))*cos(x(8)))-...
sin(x(5))*(cos(x(8))*sin(x(6))*sin(x(7))+cos(x(6))*sin(x(8)))),...
cos(x(4))*(-((0.01+cos(x(7))*cos(x(8)))*sin(x(5)))-...
cos(x(5))*(cos(x(8))*sin(x(6))*sin(x(7))+cos(x(6))*sin(x(8)))),...
sin(x(4))*(cos(x(8))*sin(x(6))*sin(x(7))+cos(x(6))*sin(x(8)))-...
cos(x(4))*sin(x(5))*(cos(x(6))*cos(x(8))*sin(x(7))-sin(x(6))*sin(x(8))),...
-(cos(x(6))*cos(x(7))*cos(x(8))*sin(x(4)))+...
cos(x(4))*(-(cos(x(7))*cos(x(8))*sin(x(5))*sin(x(6)))-...
cos(x(5))*cos(x(8))*sin(x(7))),...
sin(x(4))*(cos(x(8))*sin(x(6))+cos(x(6))*sin(x(7))*sin(x(8)))+...
cos(x(4))*(-(cos(x(5))*cos(x(7))*sin(x(8)))-...
sin(x(5))*(cos(x(6))*cos(x(8))-sin(x(6))*sin(x(7))*sin(x(8))))]]...
;

end